---
title: "Microscope agnosticism and the characterization of sedimentary abrasion of
  flint stone tools"
output:
    md_document:
      variant: gfm
bibliography: "References.bib"
csl: "elsevier-harvard.csl"
link-citations: true
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Guillermo Bustos-Pérez $^{1,2,3}$, Andreu Olle $^{2,3}$    



<div align="justify">   

## Abstract   

The surface of lithic stone tools from Paleolithic archaeological sites can suffer different postdepositional alterations, such as sedimentary erosion induced by water displacement or wind. The surface of flint artifacts can record these alterations as changes in the texture. Microscopic analysis and grayscale images can be employed to obtain quantitative data to help determine the degree of alteration undergone by the surface of a flint stone tool. However, surface quantitative values depend directly on the image capturing system of each microscope. This raises the question regarding if the quantitative values are actually capturing the evolution of a surface, if they are dependent on the type of microscope and its image capturing system, and if the detection of the degree of abrasion will vary depending on the type of microscope. The present work sets to determine if data extracted from images from two different microscopes show the same trends in surface change when postdepositional alterations occur. Surface photographs of a sample of 25 flakes were taken using a Dino-Lite Edge 3.0 AM73915MZT and a 3D Optical Profiler Sensofar S neox 090. These flakes represented three different stages of alteration (fresh, ten hours of experimentally induced sedimentary erosion, and geological neocortex). Results of quantitative values from grayscale level images indicate that, despite providing different numeric ranges, quantitative values from images of both types of microscopes reflect the same trends in surface change. The classification accuracy of the three stages of slurry erosion did not vary between microscopes.

**Key words**: microscopic analysis; lithic analysis; lithic taphonomy; post-depositional surface modifications   

## Introduction     

Flint stone tools are some of the most common remains from Paleolithic sites. They provide information about chrono-cultural developments along with the behavioral and spatial organization of Paleolithic groups. However, stone tools from Paleolithic sites might suffer a series of postdepositional alterations, with water flow or wind abrasion being some of the most common [@byers_flake_2015; @hosfield_flake_2016; @michel_freezing_2019; @petraglia_water_1994; @schick_stone_1986]. These postdepositional alterations can disrupt archaeological remains, resulting in horizontal and vertical mixing of artifacts, with on unreliable chrono-cultural interpretations. As a result of this, a good analysis of lithic assemblage integrity is needed prior to its interpretation.    

On stone tools, postdepositional alterations and their intensity are recorded on the surface, with increasing ridge width and surface abrasion being two of the most common features observed [@burroni_surface_2002; @bustos-perez_experimental_2019; @bustos-perez_quantification_2024; @chambers_like_2016; @article{shackley_stream_1974]. Unaided visual assessments of sedimentary abrasion (rounding) can result in an error ratio above 80%, indicating the need for microscope assistance through quantitative variables [@chambers_like_2016].   


Quantitative characterization of surfaces is an important part of different lithic microscopic analytical approaches. Recent traceological studies commonly use surface texture quantification for the identification of worked materials [@evans_laser_2008; @ibanez_identifying_2019; @ibanez_quantitative_2021; @macdonald_application_2014; @sferrazza_grey_2023; @stemp_discrimination_2011; @stevens_practical_2010], or for testing different models of polish development [@ibanez_quantitative_2021]. Another area of lithic microscopic analysis were surface quantification plays a key role is the identification, characterization and estimation of the intensity of post-depositional alterations on lithic artefacts [@burroni_surface_2002; @bustos-perez_experimental_2019; @caux_aspects_2018; @chambers_like_2016; @chu_micro-abrasion_2015; @hiscock_need_1985; @hosfield_interpreting_2000; @levi_sala_use_1986]. The development of these analysis has been incorporated to studies focusing on the integrity of lithic artefacts present at archaeological assemblages [@fraile-marquez_facing_2022; @galland_quantifying_2019; @staurset_post-depositional_2023].   

Recent approaches using sequential experimentation, grayscale images [@bustos-perez_quantification_2024; @sferrazza_grey_2023] and texture metrics [@haralick_textural_1973] have shown the possibility of quantifying the surface changes due to sedimentary abrasion on flint stone tools. However, the information contained in the pixels of a photograph might vary, depending on the capturing system of each microscope. This rises the issue of “microscope agnosticism” (the quality of metric values or trends to be invariant to the choice of microscope). In the present study, four aspects are explored to address the issue of microscope agnosticism in sedimentary abrasion. 


## References   


</div> 